CREATE TABLE IF NOT EXISTS CLIENTE (
  id_cliente INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) DEFAULT NULL,
  endereco INT(10) DEFAULT NULL,
  cpf int(11) DEFAULT NULL,
  rg int(10) DEFAULT NULL,
  doc INT(10) DEFAULT NULL,
  email VARCHAR(45) DEFAULT NULL,
  cel int(9) DEFAULT NULL,
  convite INT(1) DEFAULT 0,
  senha VARCHAR(8) DEFAULT NULL,
  data_cadastro date NOT NULL,
  PRIMARY KEY (id_cliente)
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS CONTA (
 id_conta INT(11) NOT NULL AUTO_INCREMENT,
 id_cliente INT(11) NOT NULL,
 limite decimal(10,2) NOT NULL,
 renda decimal(10,2) NOT NULL,
 saldo decimal(10,2) NOT NULL,
 status int(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY (id_conta)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS DOCUMENTACAO (
 id_doc INT(11) NOT NULL AUTO_INCREMENT,
 id_cliente INT(11) NOT NULL,
 foto VARCHAR(50) NOT NULL,
 doc_frente VARCHAR(50) NOT NULL,
 doc_verso VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_doc)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS ENDERECO (
 id_cliente INT(11) NOT NULL,
 rua VARCHAR(45) DEFAULT NULL,
 num INT(10) DEFAULT NULL,
 complemento VARCHAR(45) DEFAULT NULL,
 cep INT(10) DEFAULT NULL,
 cidade VARCHAR(15) DEFAULT NULL,
 estado VARCHAR(2) DEFAULT NULL, 
  PRIMARY KEY (id_cliente)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS CARTAO (
 id_cartao INT(11) NOT NULL AUTO_INCREMENT,
 numero INT(16) NOT NULL,
 validade date NOT NULL,
 criacao date NOT NULL,
 codigo INT(3) NOT NULL,
 nome_cliente VARCHAR(15) NOT NULL,
 bandeira VARCHAR(15) NOT NULL,
  PRIMARY KEY (id_cartao)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;